"""Remove coluna email da tabela lugares

Revision ID: 8c45e7dacd16
Revises: 80d7b3fa2ba7
Create Date: 2025-08-26 23:24:47.094864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c45e7dacd16'
down_revision: Union[str, None] = '80d7b3fa2ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clientes_id', table_name='lugares')
    op.create_index(op.f('ix_lugares_id'), 'lugares', ['id'], unique=False)
    op.drop_column('lugares', 'telefone')
    op.drop_column('lugares', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lugares', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lugares', sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_lugares_id'), table_name='lugares')
    op.create_index('ix_clientes_id', 'lugares', ['id'], unique=False)
    # ### end Alembic commands ###
