"""Adicionar a coluna ativo na tabela lugar

Revision ID: 91ad746be777
Revises: 8c45e7dacd16
Create Date: 2025-08-27 00:17:15.739434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ad746be777'
down_revision: Union[str, None] = '8c45e7dacd16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lugares', sa.Column('ativo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lugares', 'ativo')
    # ### end Alembic commands ###
